### ISSUE TITLE
Code tidy up time?

### ISSUE THREAD

**Issue by daN4cat** [reportico-web/reportico#13]
Checking the current code layout in master I have the following questions:

- javascripts and js dirs, are both required or can everything go in one? (better js if there is a choice)
- css and stylesheet dirs, both required?
- fdpf and tcpdf dirs, both required? what is what?
- templates and templates_c dirs, both required?
- all php files in the root directory, is that required or can things go in such way there is an entry point (index.php, partial.php, embedded.php) and the rest of the files can go into a library dir?
- can the diff file be removed?

**Comment by reportico-web** [comment]
Hi there .. 

> javascripts and js dirs, are both needed or can everything go in one? (better js if there is a choice)

 - javascripts should be deleted .. overlib is referenced in swpanel for use as a tooltip but this is never used or documented so that reference can go

> css and stylesheet dirs, both required?

- stylesheet is not required, but also old stylesheets like css/greentheme.css are also not required

> fdpf and tcpdf dirs, both required? what is what?

- Ok fpdf library was original pdf generator and is fast, some people still like this, but tcpdf is more powerful in terms of styling and is most used but is slower on big reports. So both are needed. These are customised versions of those libraries so cant be easily upgraded. In future i plan to use allow pdf generation using TornadoJS and associated php library

> templates and templates_c dirs, both required?

These are used by the smarty library, and are both necessary, id love to replace thetemplating with something more modern like twig 

> all php files in the root directory, is that required or can things go in such way there is an entry point (index.php, partial.php, embedded.php) and the rest of the files can go into a library dir?

- Personally i would prob prefer in library, also the names of the files should be changed to reflect the actual classes .. also probably files like reportico.php that contain many classes could be split.

can the diff file be removed?
Yes

Do you have nay views on namespaces or autoloading here?

**Comment by daN4cat** [comment]
Do you plan to tidy up and restructure a bit the code?

**Comment by daN4cat** [comment]
Also, have you ever considered to minify .js and .css?
That could be achieved running a grunt script.

**Comment by daN4cat** [comment]
Forgot to answer the point namespace and autoloading, I think that the dir structure of reportico should follow composer one with public/, vendor/ and therefore autoload is required.

**Comment by reportico-web** [comment]
Ok thanks, I def do plan to restructure and refactor code in near future .. I havent considered minify but keen to do it. I think to get towards autoload I would need to split all the classfiles and name them properly. and i guess have the same naming convention for files say the smarty folder which end in class.php instead of just php. 

Regarding composer, as Reportico is provided as a standalone project ( as well as plugins ) is that what the public folder is used for? So if someone wanted to use Reportico standalone, they would point their browser at public and it would then autoload everything. Sounds good if so? 

Also, by going this route i guess I could use /config area for customising configuration..

Ok, I understand you are busy so if you do provide any advice or  improvements, they are much appreciated

**Comment by daN4cat** [comment]
@reportico-web yes, you point to public so the installation is safer (security wise).

You can check the project I'm an active contributor: https://github.com/jekkos/opensourcepos/ it uses that structure with public/ and vendor/, application/ is all the software based on codeigniter.

After having create the codeigniter-reportico composer package I would like to add reportico as advanced reporting tool for that POS solution.
However I need to be careful here about the licenses, as OSPOS is MIT and I see you have GPL. Not a problem for me but people might like it or not, and might not want to have GPL code in OSPOS as forcing them to make public all their additions.

**Comment by daN4cat** [comment]
I think I can close this because I see a lot went in with the refactoring of the new beta 6.0.0.

**Comment by reportico-web** [comment]
Thats a shame. The phantomjs headless browser allows me to apply the same styles across HTML and PDF, i was considering using the chromium library https://github.com/chrome-php/headless-chromium-php but it looks quite young, but might be a better option as it looks like its under active development and that also look like it installs symphony

**Comment by daN4cat** [comment]
WRT to license, maybe MIT makes it easy but there is not that much you could do to enforce one or the other anyway.
Unless you scan all the web, how are you going to spot any installation that was modified and you didn't have the code?

**Comment by daN4cat** [comment]
I noticed that the folder images is in the root and under assets. Maybe the one under assets should be kept.

**Comment by reportico-web** [comment]
Yes you are right that, i can remove that.

Regarding license, I think Im not worried about getting back other people's code modifications, but as I have 4 contributors including you, I think to move to MIT I think I need all your approval ? Despite most of that code actually not still being in the next release.

**Comment by daN4cat** [comment]
Re license, it's fine from my side but I made a small contribution.

Re folders, also javascript is that required to be outside assets/js ?

**Comment by reportico-web** [comment]
The idea really is that the themes folders have all css and images .. so il look to remove those in assets and in the root folder.
For info are you trying to embed this version into your codeigniter module? or are you just checking in out for the moment.

If you are trying to embed it in codeigniter just wanted to point you at the laravel reportico module main file 

[https://github.com/reportico-web/laravel-reportico/blob/reportico-new-architecture/src/Reportico/Reportico/ReporticoServiceProvider.php](https://github.com/reportico-web/laravel-reportico/blob/reportico-new-architecture/src/Reportico/Reportico/ReporticoServiceProvider.php)

I dont know if codeigniter is similar but this shows (apologies if you already worked this out ):-

- overriding of ReporticoSession class to use framework specific session handling
- reportico_ajax_script_url setting to route all ajax requests through framework index.php
- passing a csrf token required by frameworks ( reportico.js needs to be modified )
- using a framework specific config function to pick up system config defaults
- passing of current user in 
- publishing web assets
- use of theme folder and projects folder within a separate framework storage path
