### ISSUE TITLE
What is the license for the Reportico.

### ISSUE THREAD

**Issue by rt-betty** [reportico-web/reportico#34]
Hi Peter,
The license I see on the following URL is GPL2.0. It is not allowed to modify source code.   
http://www.reportico.org/site/index.php/reportico-license
But you replied earlier that it was MIT license. Which one is correct, please?

![图片](https://user-images.githubusercontent.com/67623247/86860116-d5d1b680-c0f6-11ea-9f4f-56d5b8c09341.png)

**Comment by reportico-web** [comment]
Hi there that link is quite old and the actual license in the repo is now MIT... see here https://github.com/reportico-web/reportico/blob/master/LICENSE
 i need to remove that web page or at least change it. I moved it from GPL to MIT quite a few yeas ago and I was able to do this because at that point it was solely contributed to by me and I made sure I took out any GPL dependencies.

Hope that puts your mind at rest

**Comment by rt-betty** [comment]
Thank you for such a fast response.  
I have no more questions.
